# Generated by Django 6.0.2 on 2026-03-07 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_train_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='train',
            name='price',
        ),
        migrations.RemoveField(
            model_name='train',
            name='total_seats',
        ),
        migrations.CreateModel(
            name='TrainClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('GEN', 'General'), ('SL', 'Sleeper'), ('3A', 'AC 3 Tier'), ('2A', 'AC 2 Tier'), ('1A', 'AC First Class')], max_length=5)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='trains.train')),
            ],
            options={
                'unique_together': {('train', 'class_type')},
            },
        ),
    ]
