# Generated by Django 6.0.2 on 2026-03-07 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_remove_train_available_seats_remove_train_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_seats', models.IntegerField()),
                ('train_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='trains.trainclass')),
            ],
            options={
                'unique_together': {('train_class', 'date')},
            },
        ),
    ]
