# Generated by Django 4.2.11 on 2026-03-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_trainavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainavailability',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainclass',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
