# Generated by Django 6.0.2 on 2026-03-07 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('trains', '0003_remove_train_available_seats_remove_train_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='train_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trains.trainclass'),
        ),
    ]
